FROM node:lts-alpine as dependencies
WORKDIR /app
COPY package*.json ./
RUN npm i -s

FROM node:lts-alpine as builder
WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN npm run build

FROM node:lts-alpine as running
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/*.json ./
COPY --from=builder /app/.env ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE ${API_PORT}
CMD [ "npm", "run", "start:prod" ]